- id: 1
  name: app
  info: Application Server
  port: 8080
  
- id: 2
  name: prod-dns
  info: DNS

- id: 3
  name: database
  info: Database Server
  type: mysql

- id: 4
  name: utility
  info: Utility Server

- id: 5
  name: backup
  info: Backup Server

- id: 6
  name: sftp
  info: Secure File Transfer

- id: 7
  name: load_balancer
  info: Load Balancer

